GET http://localhost:3001

###

GET http://localhost:3001/api/data

###


GET http://localhost:3001/api/data/22

###


GET http://localhost:3001/api/post/2021/03

###


GET http://localhost:3001/api?sortBy=Nama

###

GET http://localhost:3001/api/peserta

###

GET http://localhost:3001/api/peserta/11

###

POST http://localhost:3001/api/peserta
content-type: application/json

{
    "name": "tutik"
}
###

DELETE  http://localhost:3001/api/peserta/1

